"""
Synthetic Document Generator for the Line Detector (Model 2)
─────────────────────────────────────────────────────────────────────────────
Builds full-page training documents from the existing single-line OCR dataset.

Each sample is generated by:
  1. Sampling 3–18 random line images from the parquet dataset
  2. Pasting them onto a canvas with random spacing, indentation, and scale
  3. Recording the exact bounding box of every pasted line

Because WE place the lines, the ground-truth text mask is free and pixel-
perfect — no manual annotation is ever needed.

Augmentations (so the detector survives real certificates, not just clean
white scans):
  - Background: white / cream / light gray / vertical gradient / color wash
  - Decorative border bands (simulates certificate frames)
  - Random "logo" blobs (circles/rectangles) that the mask marks as NON-text,
    teaching the detector to ignore seals and emblems
  - Gaussian noise, blur, brightness jitter

Output of the Dataset: (image_tensor (1,H,W), mask_tensor (1,H,W))
  image is grayscale via min-channel (matches the inference pipeline)
  mask is 1.0 where a text line is, 0.0 elsewhere

CLI (dump samples to disk for visual inspection):
    python data/synthesize_documents.py --parquet data/train.parquet \
        --out_dir outputs/synth_preview --num 12
"""

import io
import argparse
import random
from typing import List, Tuple, Optional

import numpy as np
import pandas as pd
from PIL import Image, ImageDraw, ImageFilter

import torch
from torch.utils.data import Dataset


# ── Line image loading ────────────────────────────────────────────────────────

def _decode_image(img_data) -> Image.Image:
    """Decode a parquet image cell (bytes / dict / PIL) to RGB PIL."""
    if isinstance(img_data, dict) and "bytes" in img_data:
        return Image.open(io.BytesIO(img_data["bytes"])).convert("RGB")
    if isinstance(img_data, (bytes, bytearray)):
        return Image.open(io.BytesIO(img_data)).convert("RGB")
    if isinstance(img_data, Image.Image):
        return img_data.convert("RGB")
    raise ValueError(f"Unsupported image cell type: {type(img_data)}")


class LinePool:
    """
    Holds the parquet line images in memory (as compressed bytes — decoded
    lazily per sample) and serves random lines.
    """

    def __init__(self, parquet_path: str, max_lines: Optional[int] = None):
        df = pd.read_parquet(parquet_path, columns=["image"])
        if max_lines and len(df) > max_lines:
            df = df.sample(max_lines, random_state=0).reset_index(drop=True)
        self.cells = df["image"].tolist()
        if not self.cells:
            raise ValueError(f"No rows found in {parquet_path}")

    def __len__(self):
        return len(self.cells)

    def random_line(self, rng: random.Random) -> Image.Image:
        return _decode_image(self.cells[rng.randrange(len(self.cells))])


# ── Backgrounds & decorations ─────────────────────────────────────────────────

def _random_background(w: int, h: int, rng: random.Random) -> Image.Image:
    """Generate a document background: plain, gradient, or color-washed."""
    choice = rng.random()
    if choice < 0.45:                                   # plain paper
        v = rng.randint(235, 255)
        return Image.new("RGB", (w, h), (v, v, v))
    if choice < 0.65:                                   # warm cream paper
        return Image.new("RGB", (w, h),
                         (rng.randint(240, 255), rng.randint(235, 250), rng.randint(215, 240)))
    if choice < 0.85:                                   # vertical gradient
        top    = np.array([rng.randint(225, 255)] * 3, dtype=float)
        bottom = np.array([rng.randint(200, 245)] * 3, dtype=float)
        t   = np.linspace(0, 1, h)[:, None, None]
        arr = (top * (1 - t) + bottom * t) * np.ones((h, w, 3))
        return Image.fromarray(arr.astype(np.uint8))
    # light color wash (e.g. pale blue / pink certificate paper)
    base = [rng.randint(225, 250) for _ in range(3)]
    base[rng.randrange(3)] = rng.randint(200, 230)
    return Image.new("RGB", (w, h), tuple(base))


def _add_border_band(canvas: Image.Image, rng: random.Random) -> None:
    """Draw a colored frame around the page — simulates certificate borders."""
    w, h = canvas.size
    draw  = ImageDraw.Draw(canvas)
    band  = rng.randint(max(4, w // 60), max(8, w // 18))
    color = tuple(rng.randint(40, 180) for _ in range(3))
    draw.rectangle([0, 0, w - 1, band], fill=color)               # top
    draw.rectangle([0, h - band, w - 1, h - 1], fill=color)       # bottom
    draw.rectangle([0, 0, band, h - 1], fill=color)               # left
    draw.rectangle([w - band, 0, w - 1, h - 1], fill=color)       # right


def _add_fake_logo(canvas: Image.Image, rng: random.Random,
                   forbidden: List[Tuple[int, int, int, int]]) -> None:
    """
    Draw a logo/seal-like blob that must NOT appear in the text mask.
    Placed only where it doesn't overlap existing text boxes — teaches the
    detector that compact graphics are background.
    """
    w, h  = canvas.size
    size  = rng.randint(h // 14, h // 7)
    for _ in range(10):                                  # try to find free spot
        x0 = rng.randint(0, max(1, w - size))
        y0 = rng.randint(0, max(1, h - size))
        box = (x0, y0, x0 + size, y0 + size)
        if not any(_boxes_overlap(box, fb) for fb in forbidden):
            break
    else:
        return                                           # no free spot — skip

    draw  = ImageDraw.Draw(canvas)
    color = tuple(rng.randint(30, 160) for _ in range(3))
    if rng.random() < 0.6:
        draw.ellipse(box, outline=color, width=rng.randint(3, 8))
        inner = rng.randint(2, 6)
        draw.ellipse([box[0] + size // inner, box[1] + size // inner,
                      box[2] - size // inner, box[3] - size // inner],
                     outline=color, width=2)
    else:
        draw.rectangle(box, fill=color)


def _boxes_overlap(a, b) -> bool:
    return not (a[2] < b[0] or b[2] < a[0] or a[3] < b[1] or b[3] < a[1])


# ── Core document synthesis ───────────────────────────────────────────────────

def synthesize_document(
    pool: LinePool,
    rng: random.Random,
    canvas_size: int = 512,
) -> Tuple[Image.Image, np.ndarray]:
    """
    Build one synthetic document.

    Returns:
        canvas : RGB PIL image  (canvas_size × canvas_size)
        mask   : float32 array (canvas_size × canvas_size), 1.0 on text lines
    """
    W = H = canvas_size
    canvas = _random_background(W, H, rng)

    if rng.random() < 0.35:
        _add_border_band(canvas, rng)

    mask = np.zeros((H, W), dtype=np.float32)
    text_boxes: List[Tuple[int, int, int, int]] = []

    margin_x = rng.randint(W // 20, W // 6)
    margin_y = rng.randint(H // 20, H // 8)
    y = margin_y

    n_lines     = rng.randint(3, 18)
    line_height = rng.randint(H // 36, H // 16)          # ~14–32 px at 512

    for _ in range(n_lines):
        if y + line_height >= H - margin_y:
            break

        line = pool.random_line(rng)
        lw, lh = line.size
        new_w = max(8, int(lw * line_height / lh))

        max_w = W - 2 * margin_x
        if new_w > max_w:
            new_w = max_w
        line = line.resize((new_w, line_height), Image.BICUBIC)

        # indentation: left-aligned, centred, or random indent
        align = rng.random()
        if align < 0.5:
            x = margin_x
        elif align < 0.8:
            x = margin_x + (max_w - new_w) // 2          # centred
        else:
            x = margin_x + rng.randint(0, max(0, max_w - new_w))

        canvas.paste(line, (x, y))
        mask[y:y + line_height, x:x + new_w] = 1.0
        text_boxes.append((x, y, x + new_w, y + line_height))

        gap = rng.randint(max(3, line_height // 4), int(line_height * 1.6))
        y  += line_height + gap

    # graphics that the mask marks as background
    for _ in range(rng.randint(0, 2)):
        _add_fake_logo(canvas, rng, text_boxes)

    # photometric augmentation
    if rng.random() < 0.4:
        canvas = canvas.filter(ImageFilter.GaussianBlur(radius=rng.uniform(0.3, 1.0)))
    if rng.random() < 0.5:
        arr   = np.array(canvas).astype(np.int16)
        noise = rng.gauss(0, 1)                          # per-image noise scale
        arr  += np.random.normal(0, abs(noise) * 4 + 2, arr.shape).astype(np.int16)
        canvas = Image.fromarray(np.clip(arr, 0, 255).astype(np.uint8))

    return canvas, mask


def to_min_channel(img: Image.Image) -> np.ndarray:
    """min(R,G,B) grayscale — matches the inference preprocessing."""
    return np.array(img.convert("RGB")).min(axis=2).astype(np.uint8)


# ── Torch Dataset (on-the-fly generation = unlimited training variety) ───────

class SyntheticDocumentDataset(Dataset):
    """
    Args:
        parquet_path : single-line OCR parquet (same one used to train Model 1)
        epoch_size   : virtual length — how many samples one epoch yields
        canvas_size  : square document size in px (512 recommended)
        seed         : base seed; None → fully random every epoch (train),
                       fixed int → deterministic set (validation)
    """

    def __init__(
        self,
        parquet_path: str,
        epoch_size: int = 2000,
        canvas_size: int = 512,
        seed: Optional[int] = None,
        max_lines: Optional[int] = None,
    ):
        self.pool        = LinePool(parquet_path, max_lines=max_lines)
        self.epoch_size  = epoch_size
        self.canvas_size = canvas_size
        self.seed        = seed

    def __len__(self):
        return self.epoch_size

    def __getitem__(self, idx):
        rng = random.Random(self.seed + idx) if self.seed is not None else random.Random()
        canvas, mask = synthesize_document(self.pool, rng, self.canvas_size)

        gray = to_min_channel(canvas).astype(np.float32) / 255.0
        img_t  = torch.from_numpy(gray).unsqueeze(0)            # (1, H, W)
        mask_t = torch.from_numpy(mask).unsqueeze(0)            # (1, H, W)
        return img_t, mask_t


# ── CLI preview ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import os

    p = argparse.ArgumentParser(description="Preview synthetic detector training data")
    p.add_argument("--parquet", required=True, help="Path to single-line OCR parquet")
    p.add_argument("--out_dir", default="outputs/synth_preview")
    p.add_argument("--num", type=int, default=12)
    p.add_argument("--canvas_size", type=int, default=512)
    args = p.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    pool = LinePool(args.parquet)
    print(f"[Pool] {len(pool)} line images loaded from {args.parquet}")

    for i in range(args.num):
        rng = random.Random(i)
        canvas, mask = synthesize_document(pool, rng, args.canvas_size)
        canvas.save(os.path.join(args.out_dir, f"doc_{i:03d}.png"))
        Image.fromarray((mask * 255).astype(np.uint8)).save(
            os.path.join(args.out_dir, f"doc_{i:03d}_mask.png"))

    print(f"[Done] {args.num} document/mask pairs written to {args.out_dir}")
